/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projet_Thees;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.BorderFactory;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

/**
 *
 * @author martincorria
 */
public class JF_Thees extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(JF_Thees.class.getName());

    private static final int N = Grille.TAILLE;
    private final Game game = new Game();

    private JPanel gridPanel;
    private JLabel[][] cells;

    public JF_Thees() {
        initComponents();
        buildUI();
        setupKeyBindings();
        render();
    }

    private void buildUI() {
        getContentPane().removeAll();
        getContentPane().setLayout(new BorderLayout(10, 10));

        JPanel top = new JPanel(new FlowLayout(FlowLayout.LEFT));
        top.add(new JLabel("Threes"));
        getContentPane().add(top, BorderLayout.NORTH);

        gridPanel = new JPanel(new GridLayout(N, N, 10, 10));
        gridPanel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        gridPanel.setBackground(Color.WHITE);

        cells = new JLabel[N][N];
        Font f = new Font("SansSerif", Font.BOLD, 22);

        for (int r = 0; r < N; r++) {
            for (int c = 0; c < N; c++) {
                JLabel cell = new JLabel("", JLabel.CENTER);
                cell.setOpaque(true);
                cell.setBackground(new Color(230, 230, 230));
                cell.setFont(f);
                cell.setPreferredSize(new Dimension(80, 80));
                cell.setBorder(BorderFactory.createLineBorder(new Color(200, 200, 200)));
                cells[r][c] = cell;
                gridPanel.add(cell);
            }
        }

        getContentPane().add(gridPanel, BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);

        revalidate();
        repaint();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    private void setupKeyBindings() {
        JComponent root = getRootPane();
        InputMap im = root.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = root.getActionMap();

        im.put(KeyStroke.getKeyStroke("LEFT"), "left");
        im.put(KeyStroke.getKeyStroke("RIGHT"), "right");
        im.put(KeyStroke.getKeyStroke("UP"), "up");
        im.put(KeyStroke.getKeyStroke("DOWN"), "down");

        am.put("left", new AbstractAction() {
            @Override public void actionPerformed(ActionEvent e) {
                game.jouerCoup(Direction.LEFT);
                render();
            }
        });
        am.put("right", new AbstractAction() {
            @Override public void actionPerformed(ActionEvent e) {
                game.jouerCoup(Direction.RIGHT);
                render();
            }
        });
        am.put("up", new AbstractAction() {
            @Override public void actionPerformed(ActionEvent e) {
                game.jouerCoup(Direction.UP);
                render();
            }
        });
        am.put("down", new AbstractAction() {
            @Override public void actionPerformed(ActionEvent e) {
                game.jouerCoup(Direction.DOWN);
                render();
            }
        });
    }

    private void render() {
        Grille g = game.getGrille();
        for (int r = 0; r < N; r++) {
            for (int c = 0; c < N; c++) {
                int v = g.getValeur(r, c);
                cells[r][c].setText(v == 0 ? "" : String.valueOf(v));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        java.awt.EventQueue.invokeLater(() -> new JF_Thees().setVisible(true));
    }
} 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

